/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as AboutBrandsRouteImport } from './routes/about.brands'
import { Route as AboutCeoRouteImport } from './routes/about.ceo'
import { Route as AboutCertificationsRouteImport } from './routes/about.certifications'
import { Route as AboutHistoryRouteImport } from './routes/about.history'
import { Route as AboutMissionRouteImport } from './routes/about.mission'
import { Route as AboutTestimonialsRouteImport } from './routes/about.testimonials'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as ProductsIdRouteImport } from './routes/products.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBrandsRoute = AboutBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AboutRoute,
} as any)
const AboutCeoRoute = AboutCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AboutRoute,
} as any)
const AboutCertificationsRoute = AboutCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => AboutRoute,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AboutRoute,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AboutRoute,
} as any)
const AboutTestimonialsRoute = AboutTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AboutRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/about/brands': typeof AboutBrandsRoute
  '/about/ceo': typeof AboutCeoRoute
  '/about/certifications': typeof AboutCertificationsRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/about/brands': typeof AboutBrandsRoute
  '/about/ceo': typeof AboutCeoRoute
  '/about/certifications': typeof AboutCertificationsRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/brands': typeof BrandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/about/brands': typeof AboutBrandsRoute
  '/about/ceo': typeof AboutCeoRoute
  '/about/certifications': typeof AboutCertificationsRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/testimonials': typeof AboutTestimonialsRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/order-success'
    | '/products'
    | '/services'
    | '/signup'
    | '/about/brands'
    | '/about/ceo'
    | '/about/certifications'
    | '/about/history'
    | '/about/mission'
    | '/about/testimonials'
    | '/brands/$slug'
    | '/products/$id'
    | '/brands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/order-success'
    | '/products'
    | '/services'
    | '/signup'
    | '/about/brands'
    | '/about/ceo'
    | '/about/certifications'
    | '/about/history'
    | '/about/mission'
    | '/about/testimonials'
    | '/brands/$slug'
    | '/products/$id'
    | '/brands'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/order-success'
    | '/products'
    | '/services'
    | '/signup'
    | '/about/brands'
    | '/about/ceo'
    | '/about/certifications'
    | '/about/history'
    | '/about/mission'
    | '/about/testimonials'
    | '/brands/$slug'
    | '/products/$id'
    | '/brands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/brands': {
      id: '/about/brands'
      path: '/brands'
      fullPath: '/about/brands'
      preLoaderRoute: typeof AboutBrandsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/ceo': {
      id: '/about/ceo'
      path: '/ceo'
      fullPath: '/about/ceo'
      preLoaderRoute: typeof AboutCeoRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/certifications': {
      id: '/about/certifications'
      path: '/certifications'
      fullPath: '/about/certifications'
      preLoaderRoute: typeof AboutCertificationsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/history': {
      id: '/about/history'
      path: '/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/testimonials': {
      id: '/about/testimonials'
      path: '/testimonials'
      fullPath: '/about/testimonials'
      preLoaderRoute: typeof AboutTestimonialsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface AboutRouteChildren {
  AboutBrandsRoute: typeof AboutBrandsRoute
  AboutCeoRoute: typeof AboutCeoRoute
  AboutCertificationsRoute: typeof AboutCertificationsRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  AboutMissionRoute: typeof AboutMissionRoute
  AboutTestimonialsRoute: typeof AboutTestimonialsRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutBrandsRoute: AboutBrandsRoute,
  AboutCeoRoute: AboutCeoRoute,
  AboutCertificationsRoute: AboutCertificationsRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  AboutMissionRoute: AboutMissionRoute,
  AboutTestimonialsRoute: AboutTestimonialsRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  BrandsIndexRoute: BrandsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
